version: '3.8'
services: 
  frontend: 
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
    stdin_open: true

  backend: 
    build:
      context: ./backend
    ports: 
      - "5000:5000"
    environment:
      - FLAK_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mydb
    depends_on:
      - db

  db: 
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes: 
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: